[project]
name = "localstub"
version = "0.0.2"
description = "Local HTTP Stub for Testing"
authors = [
  { name="James Saryerwinnie", email="js@jamesls.com"},
]
license = "Apache-2.0"
readme = "README.md"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
requires-python = ">=3.12.0,<3.15.0"
dependencies = [
  "trustme>=1.1.0",
  "httptools>=0.6.0",
  "cryptography>=46.0.3",
  "rich>=14.2.0",
  "truststore>=0.10.0",
  "anyio>=4.11.0",
]

[project.urls]
Repository = "https://github.com/jamesls/localstub"
Issues = "https://github.com/jamesls/localstub/issues"
Changelog = "https://github.com/jamesls/localstub/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
  "ast-grep-cli",
  "aiohttp",
  "httpx>=0.28.0",
  "pytest>=8.4.2",
  "pytest-asyncio",
  "pytest-cov>=7.0.0",
  "pyinstrument",
  "jmeslog>=0.2.0",
  "poethepoet>=0.37.0",
  "ruff>=0.16.0",
  "pyright[nodejs]>=1.1.405",
  "hypothesis>=6.165.10",
  "zensical"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  ".cruft.json",
  ".github",
  "AGENTS.md",
  "CLAUDE.md",
  "rules",
  "scripts",
  "sgconfig.yml",
]

[tool.hatch.build.targets.wheel]
packages = ["src/localstub"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["C901", "PLR0915", "E501", "SLF001"]

[tool.ruff.format]
quote-style = "preserve"
preview = true

[tool.pytest.ini_options]
addopts = """\
    --cov localstub \
    --cov-report term-missing \
    --no-cov-on-fail \
"""

[tool.coverage.run]
branch = true
source = ["src/"]


[tool.coverage.report]
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover',
    'raise NotImplementedError',
]
exclude_also = [
    "def .*: \\.\\.\\.$",
]

[tool.pyright]
include = ["src", "docs/examples"]
exclude = ["**/__pycache__"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "All"

[tool.poe.tasks]
check = [
  { cmd = "uv run ruff check ." },
  { cmd = "uv run ruff format --diff ." },
  { cmd = "uv run pyright" },
  { cmd = "uv run ast-grep scan ." },
]
test = "uv run pytest tests/"
format-code = [
  { cmd = "uv run ruff format ." },
]
# Similar to check, but also auto fixes issues.
auto-check = [
  { cmd = "uv run ruff check --fix ." },
  { cmd = "uv run ruff format ." },
  { cmd = "uv run pyright" },
  { cmd = "uv run ast-grep scan ." },
]
prcheck = ["check", "test"]

# Uncomment if you want to add a CLI script.
[project.scripts]
lstub = "localstub.cli:main"
